export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
}

export const EMOJI_LIST: EmojiItem[] = [
  // Fruits & Vegetables
  { emoji: "🍏", name: "green apple", category: "food" },
  { emoji: "🍎", name: "red apple", category: "food" },
  { emoji: "🍐", name: "pear", category: "food" },
  { emoji: "🍊", name: "tangerine orange", category: "food" },
  { emoji: "🍋", name: "lemon", category: "food" },
  { emoji: "🍌", name: "banana", category: "food" },
  { emoji: "🍉", name: "watermelon", category: "food" },
  { emoji: "🍇", name: "grapes", category: "food" },
  { emoji: "🍓", name: "strawberry", category: "food" },
  { emoji: "🫐", name: "blueberries", category: "food" },
  { emoji: "🍈", name: "melon", category: "food" },
  { emoji: "🍒", name: "cherries", category: "food" },
  { emoji: "🍑", name: "peach", category: "food" },
  { emoji: "🥭", name: "mango", category: "food" },
  { emoji: "🍍", name: "pineapple", category: "food" },
  { emoji: "🥥", name: "coconut", category: "food" },
  { emoji: "🥝", name: "kiwi fruit", category: "food" },
  { emoji: "🍅", name: "tomato", category: "food" },
  { emoji: "🍆", name: "eggplant", category: "food" },
  { emoji: "🥑", name: "avocado", category: "food" },
  { emoji: "🥦", name: "broccoli", category: "food" },
  { emoji: "🥬", name: "leafy green", category: "food" },
  { emoji: "🥒", name: "cucumber", category: "food" },
  { emoji: "🌶️", name: "hot pepper", category: "food" },
  { emoji: "🫑", name: "bell pepper", category: "food" },
  { emoji: "🧅", name: "onion", category: "food" },
  { emoji: "🧄", name: "garlic", category: "food" },
  { emoji: "🥔", name: "potato", category: "food" },
  { emoji: "🥕", name: "carrot", category: "food" },
  { emoji: "🌽", name: "ear of corn", category: "food" },
  { emoji: "🫒", name: "olive", category: "food" },
  { emoji: "🍠", name: "roasted sweet potato", category: "food" },

  // Bakery, Food, Meals
  { emoji: "🥐", name: "croissant", category: "food" },
  { emoji: "🍞", name: "bread", category: "food" },
  { emoji: "🥖", name: "baguette bread", category: "food" },
  { emoji: "🫓", name: "flatbread", category: "food" },
  { emoji: "🥨", name: "pretzel", category: "food" },
  { emoji: "🥯", name: "bagel", category: "food" },
  { emoji: "🥞", name: "pancakes", category: "food" },
  { emoji: "🧇", name: "waffle", category: "food" },
  { emoji: "🧀", name: "cheese wedge", category: "food" },
  { emoji: "🍖", name: "meat on bone", category: "food" },
  { emoji: "🍗", name: "poultry leg chicken", category: "food" },
  { emoji: "🥩", name: "cut of meat steak", category: "food" },
  { emoji: "🥓", name: "bacon", category: "food" },
  { emoji: "🍔", name: "hamburger", category: "food" },
  { emoji: "🍟", name: "french fries", category: "food" },
  { emoji: "🍕", name: "pizza", category: "food" },
  { emoji: "🌭", name: "hot dog", category: "food" },
  { emoji: "🥪", name: "sandwich", category: "food" },
  { emoji: "🌮", name: "taco", category: "food" },
  { emoji: "🌯", name: "burrito", category: "food" },
  { emoji: "🫔", name: "tamale", category: "food" },
  { emoji: "🥙", name: "stuffed flatbread falafel", category: "food" },
  { emoji: "🧆", name: "falafel", category: "food" },
  { emoji: "🥚", name: "egg", category: "food" },
  { emoji: "🍳", name: "cooking pan fried egg", category: "food" },
  { emoji: "🥘", name: "shallow pan of food paella", category: "food" },
  { emoji: "🍲", name: "pot of food stew", category: "food" },
  { emoji: "🥣", name: "bowl with spoon cereal", category: "food" },
  { emoji: "🥗", name: "green salad", category: "food" },
  { emoji: "🍿", name: "popcorn", category: "food" },
  { emoji: "🧈", name: "butter", category: "food" },
  { emoji: "Salt", name: "salt shaker", category: "food" }, // wait let's use actual 🧂
  { emoji: "🧂", name: "salt shaker", category: "food" },
  { emoji: "🥫", name: "canned food", category: "food" },
  { emoji: "🍱", name: "bento box", category: "food" },
  { emoji: "🍘", name: "rice cracker", category: "food" },
  { emoji: "🍙", name: "rice ball onigiri", category: "food" },
  { emoji: "🍚", name: "cooked rice", category: "food" },
  { emoji: "🍛", name: "curry rice", category: "food" },
  { emoji: "🍜", name: "steaming bowl ramen noodles", category: "food" },
  { emoji: "🍝", name: "spaghetti pasta", category: "food" },
  { emoji: "🍢", name: "oden", category: "food" },
  { emoji: "Sushi", name: "sushi", category: "food" }, // actual 🍣
  { emoji: "🍣", name: "sushi", category: "food" },
  { emoji: "🍤", name: "fried shrimp tempura", category: "food" },
  { emoji: "🍥", name: "fish cake with swirl", category: "food" },
  { emoji: "🥮", name: "mooncake", category: "food" },
  { emoji: "🍡", name: "dango", category: "food" },
  { emoji: "🥟", name: "dumpling", category: "food" },
  { emoji: "🥠", name: "fortune cookie", category: "food" },
  { emoji: "🥡", name: "takeout box", category: "food" },

  // Seafood & Sweets
  { emoji: "🦀", name: "crab", category: "animals" },
  { emoji: "🦞", name: "lobster", category: "food" },
  { emoji: "🦐", name: "shrimp", category: "food" },
  { emoji: "🦑", name: "squid", category: "animals" },
  { emoji: "🦪", name: "oyster", category: "food" },
  { emoji: "🍦", name: "soft ice cream", category: "food" },
  { emoji: "🍧", name: "shaved ice", category: "food" },
  { emoji: "🍨", name: "ice cream bowl", category: "food" },
  { emoji: "🍩", name: "doughnut donut", category: "food" },
  { emoji: "🍪", name: "cookie", category: "food" },
  { emoji: "🎂", name: "birthday cake", category: "food" },
  { emoji: "🍰", name: "shortcake slice", category: "food" },
  { emoji: "🧁", name: "cupcake", category: "food" },
  { emoji: "🥧", name: "pie", category: "food" },
  { emoji: "🍫", name: "chocolate bar", category: "food" },
  { emoji: "🍬", name: "candy", category: "food" },
  { emoji: "🍭", name: "lollipop", category: "food" },
  { emoji: "🍮", name: "custard pudding", category: "food" },
  { emoji: "🍯", name: "honey pot", category: "food" },

  // Drinks & Liquid
  { emoji: "🥛", name: "glass of milk", category: "food" },
  { emoji: "☕", name: "hot beverage coffee tea", category: "food" },
  { emoji: "🫖", name: "teapot", category: "food" },
  { emoji: "🍵", name: "teacup without handle green tea", category: "food" },
  { emoji: "🍶", name: "sake set", category: "food" },
  { emoji: "🍾", name: "bottle with popping cork champagne", category: "food" },
  { emoji: "🍷", name: "wine glass", category: "food" },
  { emoji: "🍸", name: "cocktail glass martini", category: "food" },
  { emoji: "🍹", name: "tropical drink", category: "food" },
  { emoji: "🍺", name: "beer mug", category: "food" },
  { emoji: "🍻", name: "clinking beer mugs", category: "food" },
  { emoji: "🥂", name: "clinking glasses toast cheers", category: "food" },
  { emoji: "🥃", name: "tumbler glass whiskey", category: "food" },
  { emoji: "🥤", name: "cup with straw soda", category: "food" },
  { emoji: "🧋", name: "bubble tea boba", category: "food" },
  { emoji: "🧃", name: "beverage box juice", category: "food" },
  { emoji: "🧉", name: "mate drink", category: "food" },
  { emoji: "🧊", name: "ice cube", category: "food" },

  // Tools / Eating
  { emoji: "🥢", name: "chopsticks", category: "tools" },
  { emoji: "🍽️", name: "fork and knife with plate", category: "tools" },
  { emoji: "🍴", name: "fork and knife", category: "tools" },
  { emoji: "🥄", name: "spoon", category: "tools" },
  { emoji: "🔪", name: "kitchen knife", category: "tools" },
  { emoji: "🏺", name: "amphora jar", category: "tools" },

  // Sports & Awards
  { emoji: "⚽", name: "soccer ball", category: "sports" },
  { emoji: "🥈", name: "2nd place medal silver", category: "sports" },
  { emoji: "🥉", name: "3rd place medal bronze", category: "sports" },
  { emoji: "🏅", name: "sports medal", category: "sports" },
  { emoji: "🎖️", name: "military medal", category: "sports" },
  { emoji: "🏆", name: "trophy cup winner", category: "sports" },
  { emoji: "🏏", name: "cricket bat and ball", category: "sports" },
  { emoji: "🏑", name: "field hockey", category: "sports" },
  { emoji: "🏒", name: "ice hockey", category: "sports" },
  { emoji: "🥍", name: "lacrosse", category: "sports" },
  { emoji: "🏓", name: "ping pong table tennis", category: "sports" },
  { emoji: "🏸", name: "badminton racket", category: "sports" },
  { emoji: "🥊", name: "boxing glove", category: "sports" },
  { emoji: "🥋", name: "martial arts uniform karate judo", category: "sports" },
  { emoji: "🥅", name: "goal net", category: "sports" },
  { emoji: "⛳", name: "flag in hole golf", category: "sports" },
  { emoji: "⛸️", name: "ice skate", category: "sports" },
  { emoji: "🎣", name: "fishing pole fish", category: "sports" },
  { emoji: "🤿", name: "diving mask snorkel", category: "sports" },
  { emoji: "🎽", name: "running shirt with sash", category: "sports" },
  { emoji: "🎿", name: "skis", category: "sports" },
  { emoji: "🛷", name: "sled", category: "sports" },
  { emoji: "🥌", name: "curling stone", category: "sports" },
  { emoji: "🎯", name: "bullseye dart target", category: "sports" },
  { emoji: "🪀", name: "yo-yo", category: "sports" },
  { emoji: " Kite", name: "kite", category: "sports" }, // actual 🪁
  { emoji: "🪁", name: "kite", category: "sports" },
  { emoji: "🎱", name: "billiards 8-ball", category: "sports" },

  // Games & Magic
  { emoji: "🔮", name: "crystal ball fortune", category: "games" },
  { emoji: "🪄", name: "magic wand wizard", category: "games" },
  { emoji: "🧿", name: "nazar amulet evil eye protection", category: "games" },
  { emoji: "🎮", name: "video game controller gamepad", category: "games" },
  { emoji: "🕹️", name: "joystick controller", category: "games" },
  { emoji: "🎰", name: "slot machine jackpot", category: "games" },
  { emoji: "🎲", name: "game die dice", category: "games" },
  { emoji: "🧩", name: "puzzle piece jigsaw", category: "games" },
  { emoji: "🧸", name: "teddy bear toy", category: "games" },
  { emoji: "🪅", name: "pinata", category: "games" },
  { emoji: "🪩", name: "mirror ball disco", category: "games" },
  { emoji: "🪆", name: "nesting dolls matryoshka", category: "games" },

  // Creative & Music
  { emoji: "🎨", name: "artist palette paint brush", category: "creative" },
  { emoji: "🖼️", name: "framed picture painting", category: "creative" },
  { emoji: "🧵", name: "thread spool sewing", category: "creative" },
  { emoji: "🪡", name: "sewing needle", category: "creative" },
  { emoji: "🧶", name: "yarn ball", category: "creative" },
  { emoji: "🪢", name: "knot string tie", category: "creative" },
  { emoji: "🎼", name: "musical score treble clef", category: "music" },
  { emoji: "🎵", name: "musical note", category: "music" },
  { emoji: "🎶", name: "musical notes", category: "music" },
  { emoji: "🎙️", name: "studio microphone recording", category: "music" },
  { emoji: "🎚️", name: "level slider volume", category: "music" },
  { emoji: "🎛️", name: "control knobs audio", category: "music" },
  { emoji: "🎤", name: "microphone sing karaoke", category: "music" },
  { emoji: "🎧", name: "headphone music audio", category: "music" },
  { emoji: "📻", name: "radio receiver tune", category: "music" },
  { emoji: "Saxophone", name: "saxophone sax instrument", category: "music" }, // 🎷
  { emoji: "🎷", name: "saxophone sax instrument", category: "music" },
  { emoji: "🪗", name: "accordion squeezebox", category: "music" },
  { emoji: "🎸", name: "guitar music string", category: "music" },
  { emoji: "🎹", name: "musical keyboard piano", category: "music" },
  { emoji: "🎺", name: "trumpet brass horn", category: "music" },
  { emoji: "🎻", name: "violin fiddle string", category: "music" },
  { emoji: "🪕", name: "banjo", category: "music" },
  { emoji: "🥁", name: "drum percussion", category: "music" },
  { emoji: "🪘", name: "long drum conga", category: "music" },

  // Tech & Electronics
  { emoji: "📱", name: "mobile phone smartphone", category: "tech" },
  { emoji: "📲", name: "mobile phone with arrow incoming call", category: "tech" },
  { emoji: "☎️", name: "telephone landline", category: "tech" },
  { emoji: "📞", name: "telephone receiver call", category: "tech" },
  { emoji: "📟", name: "pager device", category: "tech" },
  { emoji: "📠", name: "fax machine", category: "tech" },
  { emoji: "🔋", name: "battery power", category: "tech" },
  { emoji: "🪫", name: "low battery power", category: "tech" },
  { emoji: "🔌", name: "electric plug connection power", category: "tech" },
  { emoji: "💻", name: "laptop computer notebook", category: "tech" },
  { emoji: "🖥️", name: "desktop computer screen monitor", category: "tech" },
  { emoji: "🖨️", name: "printer device paper", category: "tech" },
  { emoji: "⌨️", name: "keyboard input typing", category: "tech" },
  { emoji: "🖱️", name: "computer mouse clicker", category: "tech" },
  { emoji: "💽", name: "computer disk minidisc", category: "tech" },
  { emoji: "💾", name: "floppy disk save", category: "tech" },
  { emoji: "💿", name: "optical disk cd dvd", category: "tech" },
  { emoji: "📀", name: "dvd movie disk", category: "tech" },
  { emoji: "🧮", name: "abacus math calculator", category: "tech" },
  { emoji: "🎥", name: "movie camera film", category: "tech" },
  { emoji: "🎞️", name: "film frames movie", category: "tech" },
  { emoji: "📽️", name: "film projector movie show", category: "tech" },
  { emoji: "🎬", name: "clapperboard take director film", category: "tech" },
  { emoji: "📺", name: "television tv set screen", category: "tech" },
  { emoji: "📷", name: "camera photo picture", category: "tech" },
  { emoji: "📸", name: "camera with flash photography", category: "tech" },
  { emoji: "📹", name: "video camera recorder", category: "tech" },
  { emoji: "📼", name: "videocassette vhs tape", category: "tech" },
  { emoji: "🔍", name: "magnifying glass tilted left search", category: "tech" },
  { emoji: "🔎", name: "magnifying glass tilted right find", category: "tech" },

  // Tools, Household & Science
  { emoji: "🕯️", name: "candle light flame", category: "science" },
  { emoji: "💡", name: "light bulb idea smart energy", category: "science" },
  { emoji: "🔦", name: "flashlight torch light", category: "science" },
  { emoji: "🏮", name: "red paper lantern light", category: "science" },
  { emoji: "🪔", name: "diya lamp oil light", category: "science" },
  { emoji: "🧱", name: "brick building block wall", category: "science" },
  { emoji: "🪵", name: "wood log lumber", category: "science" },
  { emoji: "🛖", name: "hut shelter cabin", category: "science" },
  { emoji: "🪓", name: "axe wood chop tool", category: "science" },
  { emoji: "🩹", name: "adhesive bandage first-aid", category: "science" },
  { emoji: "🩺", name: "stethoscope doctor medical", category: "science" },
  { emoji: "🩻", name: "x-ray bones medical radiology", category: "science" },
  { emoji: "🧬", name: "dna double helix biology gene", category: "science" },
  { emoji: "🔬", name: "microscope science lab research", category: "science" },
  { emoji: "🔭", name: "telescope astronomy space stars", category: "science" },
  { emoji: "📡", name: "satellite dish antenna communication", category: "science" },
  { emoji: "💉", name: "syringe needle injection medicine", category: "science" },
  { emoji: "🩸", name: "drop of blood donate medical", category: "science" },
  { emoji: "💊", name: "pill tablet medicine drugs capsule", category: "science" },
  { emoji: "🩼", name: "crutch injury walking support", category: "science" },
  { emoji: "🪞", name: "mirror reflection glass", category: "science" },
  { emoji: "🧳", name: "luggage suitcase travel bag", category: "science" },
  { emoji: "🌂", name: "closed umbrella rain drop protection", category: "science" },
  { emoji: "☂️", name: "umbrella rain weather protection", category: "science" },

  // Clothing & Fashion
  { emoji: "👓", name: "glasses spectacles reading eyesight", category: "fashion" },
  { emoji: "🕶️", name: "sunglasses cool shade summer", category: "fashion" },
  { emoji: "🥽", name: "goggles laboratory swim protection", category: "fashion" },
  { emoji: "🥼", name: "lab coat science medical uniform", category: "fashion" },
  { emoji: "🦺", name: "safety vest orange construction hazard", category: "fashion" },
  { emoji: "👔", name: "necktie dress shirt suit business formal", category: "fashion" },
  { emoji: "👕", name: "t-shirt tee casual wear clothing", category: "fashion" },
  { emoji: "👖", name: "jeans denim pants trousers clothing", category: "fashion" },
  { emoji: "🧣", name: "scarf winter warm neck wear", category: "fashion" },
  { emoji: "🧤", name: "gloves winter warm hand protection", category: "fashion" },
  { emoji: "🧥", name: "coat jacket outerwear winter clothing", category: "fashion" },
  { emoji: "🧦", name: "socks foot wear warm clothing", category: "fashion" },
  { emoji: "👗", name: "dress gown party wear female clothing", category: "fashion" },
  { emoji: "👘", name: "kimono traditional japanese robe", category: "fashion" },
  { emoji: "🥻", name: "sari traditional indian dress", category: "fashion" },
  { emoji: "🩱", name: "one-piece swimsuit female swim wear", category: "fashion" },
  { emoji: "🩲", name: "briefs underwear swimsuit clothing", category: "fashion" },
  { emoji: "🩳", name: "shorts casual wear trunks", category: "fashion" },
  { emoji: "👙", name: "bikini two-piece swimsuit female beach wear", category: "fashion" },
  { emoji: "👚", name: "woman's blouse top clothing", category: "fashion" },
  { emoji: "👛", name: "purse wallet coin pouch clutch bag", category: "fashion" },
  { emoji: "👜", name: "handbag purse accessories leather bag", category: "fashion" },
  { emoji: "👝", name: "clutch bag small purse pouch", category: "fashion" },
  { emoji: "🛍️", name: "shopping bags paper bag gift shop", category: "fashion" },
  { emoji: "🎒", name: "backpack rucksack travel school bag", category: "fashion" },
  { emoji: "🩴", name: "thong sandal flip-flop beach footwear", category: "fashion" },
  { emoji: "👞", name: "man's shoe leather formal footwear", category: "fashion" },
  { emoji: "👟", name: "running shoe sneaker sports footwear", category: "fashion" },
  { emoji: "🥾", name: "hiking boot winter mountain footwear", category: "fashion" },
  { emoji: "🥿", name: "flat shoe slip-on loafer footwear", category: "fashion" },
  { emoji: "👠", name: "high-heeled shoe stiletto female footwear", category: "fashion" },
  { emoji: "👡", name: "woman's sandal heels open toe footwear", category: "fashion" },
  { emoji: "👢", name: "woman's boot high long leather footwear", category: "fashion" },
  { emoji: "👑", name: "crown king queen royal gold prince princess", category: "fashion" },
  { emoji: "👒", name: "woman's hat summer sun protection", category: "fashion" },
  { emoji: "🎩", name: "top hat formal magician classic wear", category: "fashion" },
  { emoji: "🎓", name: "graduation cap college degree university mortarboard", category: "fashion" },
  { emoji: "🧢", name: "billed cap baseball hat casual wear", category: "fashion" },
  { emoji: "🪖", name: "military helmet army protection safety combat", category: "fashion" },
  { emoji: "💄", name: "lipstick makeup beauty cosmetics", category: "fashion" },
  { emoji: "💍", name: "ring diamond engagement jewelry gift marriage", category: "fashion" },
  { emoji: "💼", name: "briefcase office suitcase business leather", category: "fashion" },

  // Animals
  { emoji: "🦁", name: "lion face roar wild cat predator", category: "animals" },
  { emoji: "🐯", name: "tiger face wild cat stripes predator", category: "animals" },
  { emoji: "🐨", name: "koala bear marsupial cute gray", category: "animals" },
  { emoji: "🐻", name: "bear face grizzly brown cute wild", category: "animals" },
  { emoji: "🐺", name: "wolf face howling canine predator grey", category: "animals" },
  { emoji: " foxes", name: "fox face orange clever canine tail", category: "animals" }, // 🦊
  { emoji: "🦊", name: "fox face orange clever canine tail", category: "animals" },
  { emoji: "🦝", name: "raccoon bandit face stripes gray", category: "animals" },
  { emoji: "🐱", name: "cat face cute domestic pet meow", category: "animals" },
  { emoji: "🐈", name: "cat full body domestic pet walking felines", category: "animals" },
  { emoji: "🐆", name: "leopard cheetah big cat wild spots", category: "animals" },
  { emoji: "🐴", name: "horse face stallion equestrian", category: "animals" },
  { emoji: "🐎", name: "horse racing equestrian stallion fast runner", category: "animals" },
  { emoji: "🦄", name: "unicorn face mythical horn colorful magical horse", category: "animals" },
  { emoji: "🦓", name: "zebra stripes wild horse safari", category: "animals" },
  { emoji: "🦌", name: "deer stag antlers woodland elk", category: "animals" },
  { emoji: "🦬", name: "bison buffalo wild american native shaggy", category: "animals" },
  { emoji: "🐮", name: "cow face domestic cattle milk dairy livestock", category: "animals" },
  { emoji: "🐂", name: "ox bull domestic cattle horns livestock", category: "animals" },
  { emoji: "🐃", name: "water buffalo ox horned domestic livestock", category: "animals" },
  { emoji: "🐄", name: "cow full body spotted domestic dairy livestock", category: "animals" },
  { emoji: "🐷", name: "pig face cute domestic swine pork oink pink", category: "animals" },
  { emoji: "🐖", name: "pig full body domestic swine oink livestock", category: "animals" },
  { emoji: "🐗", name: "boar wild pig tusk swine forest", category: "animals" },
  { emoji: "🐽", name: "pig nose snout oink scent pink", category: "animals" },
  { emoji: "🐏", name: "ram sheep horns male livestock male sheep", category: "animals" },
  { emoji: "🐑", name: "ewe sheep fluffy wool white livestock", category: "animals" },
  { emoji: "🐐", name: "goat domestic horned livestock beard", category: "animals" },
  { emoji: "🐪", name: "camel dromedary one hump desert animal camelus", category: "animals" },
  { emoji: "🐫", name: "two-hump camel bactrian desert animal camelus", category: "animals" },
  { emoji: "🦙", name: "llama alpaca spit fluffy wool camelid mountain", category: "animals" },
  { emoji: "🦒", name: "giraffe tall neck spots safari savanna long-legged", category: "animals" },
  { emoji: "🐘", name: "elephant trunk ears tusk mammal big gray", category: "animals" },
  { emoji: "🦣", name: "woolly mammoth extinct tusk elephant ice-age", category: "animals" },
  { emoji: "🦏", name: "rhinoceros rhino horn big armored wild safari", category: "animals" },
  { emoji: "🦛", name: "hippopotamus hippo water big wild jaws savanna", category: "animals" },
  { emoji: "🐭", name: "mouse face cute rodent cheese squeak", category: "animals" },
  { emoji: "🐁", name: "mouse full body white rodent pet laboratory", category: "animals" },
  { emoji: "🐀", name: "rat rodent long tail pest sewer scavenger", category: "animals" },
  { emoji: "🐹", name: "hamster face cute rodent pet cheeks fluffy", category: "animals" },
  { emoji: "🐰", name: "rabbit face cute bunny long ears fluffy carrot", category: "animals" },
  { emoji: "🐇", name: "rabbit full body bunny jumping fluffy tail hare", category: "animals" },
  { emoji: "🐿️", name: "chipmunk rodent squirrel nuts acorn cute", category: "animals" },
  { emoji: "🦫", name: "beaver dam builder teeth flat tail rodent stream", category: "animals" },
  { emoji: "🦔", name: "hedgehog spines quill cute small nocturnal", category: "animals" },
  { emoji: "🦥", name: "sloth slow climbing trees cute furry hanging branch", category: "animals" },
  { emoji: "🦦", name: "otter swimming cute playful river sea aquatic", category: "animals" },
  { emoji: "🦨", name: "skunk stripe smell spray defense nocturnal stink", category: "animals" },
  { emoji: "🦘", name: "kangaroo joey pouch jump hop australia outback", category: "animals" },
  { emoji: "🦡", name: "badger burrower stripes forest tough fierce", category: "animals" },
  { emoji: "🐾", name: "paw prints track animal dog cat bear feet", category: "animals" },
  { emoji: "🦃", name: "turkey thanksgiving bird feathers gobble feast", category: "animals" },
  { emoji: "🐔", name: "chicken hen rooster domestic bird cluck eggs", category: "animals" },
  { emoji: "🐓", name: "rooster cockerel male chicken crow cock-a-doodle-do", category: "animals" },
  { emoji: "🐣", name: "hatching chick egg hatching bird baby chicken", category: "animals" },
  { emoji: "🐤", name: "baby chick yellow bird domestic farm cute", category: "animals" },
  { emoji: "🐥", name: "front-facing baby chick yellow bird farm wings", category: "animals" },
  { emoji: "🐦", name: "bird avian flying songbird wings feathers beak", category: "animals" },
  { emoji: "🐧", name: "penguin arctic bird flightless swim waddle ice", category: "animals" },
  { emoji: "🕊️", name: "dove of peace white bird olive branch flight", category: "animals" },
  { emoji: "🦅", name: "eagle bird of prey flying raptor sharp eyes wings", category: "animals" },
  { emoji: "🦆", name: "duck water bird flying swimming webbed feet quack", category: "animals" },
  { emoji: "🦢", name: "swan white water bird elegant long neck lake", category: "animals" },
  { emoji: "🦉", name: "owl nocturnal bird of prey wisdom hoot eyes", category: "animals" },
  { emoji: "🦤", name: "dodo bird extinct flightless bird island islander", category: "animals" },
  { emoji: "🦩", name: "flamingo pink long legs water bird wading marsh", category: "animals" },
  { emoji: "🦚", name: "peacock feathers colorful display fan tail bird", category: "animals" },
  { emoji: "🦜", name: "parrot tropical bird colorful talk mimic feathers", category: "animals" },
  { emoji: "🐸", name: "frog amphibian pond jump green croak toad", category: "animals" },
  { emoji: "🐊", name: "crocodile alligator swamp reptile predator jaws", category: "animals" },
  { emoji: "🐢", name: "turtle tortoise shell marine reptile ocean slow", category: "animals" },
  { emoji: "🦎", name: "lizard gecko reptile scales tail crawl sunbathing", category: "animals" },
  { emoji: "🐍", name: "snake serpent reptile hiss venom scales crawl", category: "animals" },
  { emoji: "🐲", name: "dragon face mythical fire legendary scales monster", category: "animals" },
  { emoji: "🐉", name: "dragon mythical serpentine scales wings ancient", category: "animals" },
  { emoji: "🦕", name: "sauropod long neck dinosaur herbivore ancient prehistoric", category: "animals" },
  { emoji: "🦖", name: "tyrannosaurus rex t-rex carnivore dinosaur prehistoric roar", category: "animals" },
  { emoji: "🐳", name: "spouting whale blowhole spout marine mammal ocean", category: "animals" },
  { emoji: "🐋", name: "whale massive marine mammal ocean swim baleen", category: "animals" },
  { emoji: "🐬", name: "dolphin marine mammal smart playful jumping ocean", category: "animals" },
  { emoji: "🦭", name: "seal pinniped ocean sea aquatic cute whiskers", category: "animals" },
  { emoji: "🐟", name: "fish swimming aquatic scales ocean river gills", category: "animals" },
  { emoji: "🐠", name: "tropical fish colorful reef aquarium ocean swimming", category: "animals" },
  { emoji: "🐡", name: "blowfish puffer fish spikes ocean inflate round", category: "animals" },
  { emoji: "🦈", name: "shark predator teeth fin ocean sea marine jaws", category: "animals" },
  { emoji: "🐙", name: "octopus tentacles eight legs ocean marine smart ink", category: "animals" },
  { emoji: "🦪", name: "oyster pearl shell mollusk seafood ocean bed", category: "animals" },
  { emoji: "🪼", name: "jellyfish sting translucent ocean sea drift tentacles", category: "animals" },
  { emoji: "🐌", name: "snail slow shell slimy trail slug garden crawling", category: "animals" },
  { emoji: "🦋", name: "butterfly wings colorful insect fly cocoon metamorphosis", category: "animals" },
  { emoji: "🐛", name: "bug caterpillar insect crawl garden green larva", category: "animals" },
  { emoji: "🐜", name: "ant colony insect crawl colony worker tiny", category: "animals" },
  { emoji: "🐝", name: "honeybee bee sting honey pollen insect stripe yellow", category: "animals" },
  { emoji: "🪲", name: "beetle insect scarab shell crawl bug", category: "animals" },
  { emoji: "🐞", name: "lady beetle ladybug spots red insect lucky bug", category: "animals" },
  { emoji: "🦗", name: "cricket insect chirp hop green grass jumper", category: "animals" },
  { emoji: "🪳", name: "cockroach pest insect nocturnal antenna crawl bug", category: "animals" },
  { emoji: "🕷️", name: "spider arachnid eight legs web fangs insect crawl", category: "animals" },
  { emoji: "🕸️", name: "spiderweb web sticky spider nest spun threads", category: "animals" },
  { emoji: "🦂", name: "scorpion sting venom claws desert nocturnal arachnid", category: "animals" },
  { emoji: " Mosquito", name: "mosquito insect sting bite buzz blood itch malaria", category: "animals" }, // 🦟
  { emoji: "🦟", name: "mosquito insect sting bite buzz blood itch malaria", category: "animals" },
  { emoji: "🪰", name: "fly insect wings buzz housefly pest trash bug", category: "animals" },
  { emoji: "🪱", name: "worm earthworm crawl bait garden soil slimy wiggle", category: "animals" },
  { emoji: "🦠", name: "microbe bacteria virus germ pathogen infection disease", category: "animals" },

  // Nature, Flowers & Plants
  { emoji: "🌵", name: "cactus desert spines thorns dry green plant", category: "nature" },
  { emoji: "🎄", name: "christmas tree decorated evergreen pine holiday winter", category: "nature" },
  { emoji: "🌲", name: "evergreen tree pine conifer forest woods nature", category: "nature" },
  { emoji: "🌳", name: "deciduous tree forest nature green leaves oak shade", category: "nature" },
  { emoji: "🌴", name: "palm tree tropical beach island vacation warm weather", category: "nature" },
  { emoji: "🌱", name: "seedling sprout plant grow spring garden agriculture", category: "nature" },
  { emoji: "🌿", name: "herb plant green leaves tea cooking medicine organic", category: "nature" },
  { emoji: "☘️", name: "shamrock green clover luck irish st patricks day", category: "nature" },
  { emoji: "🍀", name: "four leaf clover lucky green irish st patrick", category: "nature" },
  { emoji: "🍁", name: "maple leaf autumn fall orange red foliage canada", category: "nature" },
  { emoji: "🍂", name: "fallen leaf dry brown autumn fall foliage garden", category: "nature" },
  { emoji: "🍃", name: "leaf fluttering in wind breeze fresh green blow", category: "nature" },
  { emoji: "🪹", name: "empty nest bird home branch woods ecology", category: "nature" },
  { emoji: "🪺", name: "nest with eggs bird baby chicks home branch woodland", category: "nature" },
  { emoji: "🍄", name: "mushroom fungus toadstool red cap white spots forest", category: "nature" },
  { emoji: "🌰", name: "chestnut nut autumn fall food seed tree", category: "nature" },

  // Vehicles & Transportation
  { emoji: "🚗", name: "automobile car red vehicle road transportation drive", category: "transport" },
  { emoji: "🚕", name: "taxi yellow cab fare hire transportation drive", category: "transport" },
  { emoji: "🚙", name: "sport utility vehicle suv blue family car road trip", category: "transport" },
  { emoji: "🚌", name: "bus yellow transport mass school transit commuter", category: "transport" },
  { emoji: "🚎", name: "trolleybus electric bus overhead wires transit transport", category: "transport" },
  { emoji: "🏎️", name: "racing car formula F1 fast speed motorsport driver", category: "transport" },
  { emoji: "🚓", name: "police car patrol vehicle siren emergency law cop", category: "transport" },
  { emoji: "🚑", name: "ambulance siren medical emergency rescue hospital patient", category: "transport" },
  { emoji: "🚒", name: "fire engine truck siren rescue hose firefighter emergency", category: "transport" },
  { emoji: "🚐", name: "minibus van transport delivery white shuttle commuter", category: "transport" },
  { emoji: "🛻", name: "pickup truck flatbed cargo transport utility hauling", category: "transport" },
  { emoji: "🚚", name: "delivery truck moving cargo freight logistics package van", category: "transport" },
  { emoji: "🚛", name: "articulated lorry semi truck big rig cargo freight hauling", category: "transport" },
  { emoji: "🚜", name: "tractor farm vehicle agriculture field heavy machinery", category: "transport" },
  { emoji: "🏍️", name: "motorcycle motorbike race speed two wheels rider driver", category: "transport" },
  { emoji: "🛵", name: "motor scooter moped vespa transit city two wheels", category: "transport" },
  { emoji: "🦽", name: "manual wheelchair mobility disability medical accessibility", category: "transport" },
  { emoji: "🦼", name: "motorized wheelchair power wheelchair mobility accessibility disability", category: "transport" },
  { emoji: "🛺", name: "auto rickshaw tuk-tuk three wheels taxi transit commuter", category: "transport" },
  { emoji: "🚲", name: "bicycle bike two wheels cycling pedal sport transit", category: "transport" },
  { emoji: "🛴", name: "kick scooter push ride active transport kids commuter", category: "transport" },
  { emoji: "🛹", name: "skateboard board deck skate park active wheels sport", category: "transport" },
  { emoji: "🛼", name: "roller skate quad skates rink wheels glide recreation", category: "transport" },
  { emoji: "🚏", name: "bus stop transit station sign commuter schedule", category: "transport" },
  { emoji: "🛣️", name: "motorway highway freeway open road route drive road trip", category: "transport" },
  { emoji: "🛤️", name: "railway track train transit line rails path transport", category: "transport" },
  { emoji: "🛢️", name: "oil drum petroleum fuel barrel chemical steel container", category: "transport" },
  { emoji: "⛽", name: "fuel pump gas station petrol refill energy vehicle", category: "transport" },
  { emoji: "🚨", name: "police car light red light siren emergency alarm warning", category: "transport" },
  { emoji: "🚥", name: "horizontal traffic light stoplight signals street roads", category: "transport" },
  { emoji: "🚦", name: "vertical traffic light stoplight street roads navigation driving", category: "transport" },
  { emoji: "🛑", name: "stop sign octagon red street driving warning safety", category: "transport" },
  { emoji: "🚧", name: "construction sign barrier warning orange roadwork street", category: "transport" },
  { emoji: "⚓", name: "anchor boat ship port marine nautical navy vessel", category: "transport" },
  { emoji: "🛟", name: "ring buoy lifebuoy water rescue boat safety maritime float", category: "transport" },
  { emoji: "⛵", name: "sailboat yacht yachting wind sail vessel water sport", category: "transport" },
  { emoji: "🛶", name: "canoe kayak paddle rowing stream lake active sport", category: "transport" },
  { emoji: "🚤", name: "speedboat powerboat fast engine vessel water wake", category: "transport" },
  { emoji: "🛳️", name: "passenger ship cruise liner vacation travel ocean maritime", category: "transport" },
  { emoji: "⛴️", name: "ferry commuter boat crossing water vehicle passenger ship", category: "transport" },
  { emoji: "🛩️", name: "small airplane propeller private jet flight pilot travel", category: "transport" },
  { emoji: "✈️", name: "airplane flight commercial jet travel airport vacation tourism", category: "transport" },
  { emoji: "🛫", name: "airplane departure takeoff flight airport vacation travel", category: "transport" },
  { emoji: "🛬", name: "airplane arrival landing flight airport trip return home", category: "transport" },
  { emoji: "🪂", name: "parachute skydiving skydiver air extreme sport jump", category: "transport" },
  { emoji: "💺", name: "seat airline seat chair passenger travel class booking", category: "transport" },
  { emoji: "🚁", name: "helicopter chopper flight rotor blade aerial rescue pilot", category: "transport" },
  { emoji: "🚟", name: "suspension railway overhead train transport transit commute", category: "transport" },
  { emoji: "🚠", name: "mountain cableway ski lift transit gondola alpine transport", category: "transport" },
  { emoji: "🚡", name: "aerial tramway gondola cable car transit transit transport", category: "transport" },
  { emoji: "🚀", name: "rocket ship space launch shuttle sci-fi exploration boost", category: "transport" },
  { emoji: "🛸", name: "flying saucer ufo alien extraterrestrial spacecraft sci-fi", category: "transport" },
  { emoji: "🛰️", name: "satellite orbit space communication gps weather technology", category: "transport" },
  { emoji: "🛎️", name: "bellhop bell service reception desk hotel ring lobby", category: "transport" },

  // Time & Measurement
  { emoji: "⌛", name: "hourglass done glass sand time flowing measure duration", category: "time" },
  { emoji: "⏳", name: "hourglass not done glass sand flowing time clock countdown", category: "time" },
  { emoji: "⌚", name: "watch wrist watch analog clock time timer hand wearable", category: "time" },
  { emoji: "⏰", name: "alarm clock wake up ring alert time watch morning", category: "time" },
  { emoji: "⏱️", name: "stopwatch timer counter sports race duration runner timing", category: "time" },
  { emoji: "⏲️", name: "timer clock count dial kitchen baking cooking seconds", category: "time" },
  { emoji: "🕰️", name: "mantelpiece clock vintage antique time grandfather clock decor", category: "time" },

  // Places & Landscapes
  { emoji: "🗺️", name: "world map travel route atlas geography location trip", category: "places" },
  { emoji: "🧭", name: "compass navigation orientation directions north map explorer", category: "places" },
  { emoji: "🏔️", name: "snow-capped mountain peak high altitude ice winter alpine climb", category: "places" },
  { emoji: "⛰️", name: "mountain peak high range climb adventure nature landscape", category: "places" },
  { emoji: "🌋", name: "volcano magma lava erupting mountain active hot science", category: "places" },
  { emoji: "🗻", name: "mount fuji fujisan japanese volcano snow peak landmark", category: "places" },
  { emoji: "🏕️", name: "camping tent trees fire forest nature outdoor adventure", category: "places" },
  { emoji: "🏖️", name: "beach with umbrella sand sun beach vacation summer island", category: "places" },
  { emoji: "🏜️", name: "desert hot sun cactus dry barren sand dunes", category: "places" },
  { emoji: "🏝️", name: "desert island palm tree ocean secluded beach vacation tropical", category: "places" },
  { emoji: "🏞️", name: "national park scenic valley river mountains forest landscape", category: "places" },
  { emoji: "🏟️", name: "stadium sports arena concert field stadium seating tracks", category: "places" },
  { emoji: "🏛️", name: "classical building museum government court greek roman temple", category: "places" },
  { emoji: "🏗️", name: "building construction crane heavy building machinery structural", category: "places" },
  { emoji: "🏘️", name: "houses neighborhood suburban residential homes village street", category: "places" },
  { emoji: "🏙️", name: "cityscape skyline skyscrapers tall buildings downtown metropolis", category: "places" },
  { emoji: "🏚️", name: "derelict house abandoned ruined broken spooky haunted home", category: "places" },
  { emoji: "🏢", name: "office building commercial skyscrapers workspace agency tower", category: "places" },
  { emoji: "🏬", name: "department store mall shopping retail commercial buildings", category: "places" },
  { emoji: "🏣", name: "japanese post office building mail carrier stamp service", category: "places" },
  { emoji: "🏤", name: "european post office building mail carrier postage stamps letter", category: "places" },
  { emoji: "🏥", name: "hospital medical doctor nurse health clinic medicine ambulance", category: "places" },
  { emoji: "🏦", name: "bank building money finance coins savings check vault", category: "places" },
  { emoji: "🏨", name: "hotel building travel vacation lodging room service lobby", category: "places" },
  { emoji: "🏩", name: "love hotel room couple clock heart pink motel", category: "places" },
  { emoji: "🏪", name: "convenience store corner shop 24/7 food snacks market", category: "places" },
  { emoji: "🏫", name: "school building education class classroom students learning", category: "places" },
  { emoji: "🏭", name: "factory industrial building smokestacks energy production manufacturing", category: "places" },
  { emoji: "🏯", name: "japanese castle fortress ancient samurai roof historic landmark", category: "places" },
  { emoji: "🏰", name: "castle fortress medieval king queen prince princess stone tower", category: "places" },
  { emoji: "💒", name: "wedding church marriage chapel bride groom ceremony ring", category: "places" },
  { emoji: "🗼", name: "tokyo tower red steel tower landmark radio eiffel tower", category: "places" },
  { emoji: "🗽", name: "statue of liberty new york nyc america freedom landmark", category: "places" },
  { emoji: "⛪", name: "church christian cross religion worship faith chapel", category: "places" },
  { emoji: "🕌", name: "mosque muslim islam religion crescent moon worship dome", category: "places" },
  { emoji: "🛕", name: "hindu temple religion worship faith god deity tower", category: "places" },
  { emoji: "🕍", name: "synagogue jewish religion worship star of david faith torah", category: "places" },
  { emoji: "⛩️", name: "shinto shrine torii gate japanese religion spirit sanctuary", category: "places" },
  { emoji: "🕋", name: "kaaba mecca saudi arabia pilgrimage islam muslim prayer", category: "places" },
  { emoji: "⛲", name: "fountain water park plaza garden decorative stream splashing", category: "places" },
  { emoji: "⛺", name: "tent camping shelter outdoor sleeping mountain adventure", category: "places" },
  { emoji: "🌁", name: "foggy bridge Golden Gate bridge San Francisco fog weather", category: "places" },
  { emoji: "🌃", name: "night with stars dark starry sky city view dark night", category: "places" },
  { emoji: "🌄", name: "sunrise over mountains morning sun climbing peak daylight", category: "places" },
  { emoji: "🌅", name: "sunrise morning sun horizon orange sky lake dawn", category: "places" },
  { emoji: "🌆", name: "cityscape at dusk sunset city buildings skyline evening sky", category: "places" },
  { emoji: "🌇", name: "sunset sun setting behind city buildings horizon golden hour", category: "places" },
  { emoji: "🌉", name: "bridge at night water cityscape illuminated suspension bridge", category: "places" },
  { emoji: "♨️", name: "hot springs steam onsen bath spa japanese relaxation", category: "places" },
  { emoji: "🎠", name: "carousel horse merry-go-round amusement park fairground kids ride", category: "places" },
  { emoji: "🎡", name: "ferris wheel amusement park fairground ride height skyline", category: "places" },
  { emoji: "🎢", name: "roller coaster fast tracks loop amusement park thrill ride", category: "places" },
  { emoji: "💈", name: "barber pole red white blue stripes haircut barber salon", category: "places" },
  { emoji: "🎪", name: "circus tent big top fair carnival performances acts show", category: "places" },

  // Hearts, Love & Expressions
  { emoji: "💘", name: "heart with arrow cupid love valentines dating romance", category: "hearts" },
  { emoji: "💝", name: "heart with ribbon gift love valentine present surprise", category: "hearts" },
  { emoji: "💖", name: "sparkling heart love shining glowing romance cute", category: "hearts" },
  { emoji: "💗", name: "growing heart pulse love romance valentines pink beating", category: "hearts" },
  { emoji: "💓", name: "beating heart love vibration romance pulse pink", category: "hearts" },
  { emoji: "💞", name: "revolving hearts spinning love romance valentines couples", category: "hearts" },
  { emoji: "💕", name: "two hearts love pink cute sweet valentines couples", category: "hearts" },
  { emoji: "💟", name: "heart decoration purple frame love valentines ornament", category: "hearts" },
  { emoji: "❣️", name: "heart exclamation mark red point attention warning accent", category: "hearts" },
  { emoji: "💔", name: "broken heart sadness painful heartbreak end love divorce", category: "hearts" },
  { emoji: "❤️🔥", name: "heart on fire burning passion love desire hot romance", category: "hearts" },
  { emoji: "❤️🩹", name: "mending heart bandage heal recover health love broken", category: "hearts" },
  { emoji: "❤️", name: "red heart classic love romance passion valentines couples", category: "hearts" },
  { emoji: "🧡", name: "orange heart warmth friendship love peace comfort", category: "hearts" },
  { emoji: "💛", name: "yellow heart loyalty trust friendship happiness gold", category: "hearts" },

  // Shapes & Colored Circles
  { emoji: "🟢", name: "green circle shape status button dot safe", category: "symbols" },
  { emoji: "🔵", name: "blue circle shape status button dot info", category: "symbols" },
  { emoji: "🟣", name: "purple circle shape status button dot fancy", category: "symbols" },
  { emoji: "🟤", name: "brown circle shape status button dot soil", category: "symbols" },
  { emoji: "⚫", name: "black circle shape status button dot off dark", category: "symbols" },
  { emoji: "⚪", name: "white circle shape status button dot light blank", category: "symbols" },
  { emoji: "🟥", name: "red square shape block stop dangerous fail", category: "symbols" },
  { emoji: "🟧", name: "orange square shape block warning alert", category: "symbols" },
  { emoji: "🟨", name: "yellow square shape block caution warning wait", category: "symbols" },
  { emoji: "🟩", name: "green square shape block safe correct success", category: "symbols" },
  { emoji: "🟦", name: "blue square shape block classic color sky", category: "symbols" },
  { emoji: "🟪", name: "purple square shape block royal color fancy", category: "symbols" },
  { emoji: "🟫", name: "brown square shape block earth wood neutral", category: "symbols" },
  { emoji: "⬛", name: "black large square shape blank off screen stop", category: "symbols" },
  { emoji: "⬜", name: "white large square shape blank paper list empty", category: "symbols" },

  // Zodiac
  { emoji: "♈", name: "aries zodiac sign ram star horoscopes", category: "zodiac" },
  { emoji: "♉", name: "taurus zodiac sign bull star horoscopes", category: "zodiac" },
  { emoji: "♊", name: "gemini zodiac sign twins star horoscopes", category: "zodiac" },
  { emoji: "♋", name: "cancer zodiac sign crab star horoscopes", category: "zodiac" },
  { emoji: "♌", name: "leo zodiac sign lion star horoscopes", category: "zodiac" },
  { emoji: "♍", name: "virgo zodiac sign maiden star horoscopes", category: "zodiac" },
  { emoji: "♎", name: "libra zodiac sign scales star horoscopes", category: "zodiac" },
  { emoji: "♏", name: "scorpio zodiac sign scorpion star horoscopes", category: "zodiac" },
  { emoji: "♐", name: "sagittarius zodiac sign archer star horoscopes", category: "zodiac" },
  { emoji: "♑", name: "capricorn zodiac sign goat star horoscopes", category: "zodiac" },
  { emoji: "♒", name: "aquarius zodiac sign water bearer star horoscopes", category: "zodiac" },
  { emoji: "♓", name: "pisces zodiac sign fishes star horoscopes", category: "zodiac" },
  { emoji: "⛎", name: "ophiuchus zodiac sign serpent bearer horoscopes star", category: "zodiac" },

  // Controller UI Arrows & Media Controls
  { emoji: "🔀", name: "shuffle tracks arrows random music play", category: "controls" },
  { emoji: "🔁", name: "repeat track arrows loop continuous music play", category: "controls" },
  { emoji: "🔂", name: "repeat once track arrow single loop music play", category: "controls" },
  { emoji: "▶️", name: "play button triangle start media stream movie", category: "controls" },
  { emoji: "⏩", name: "fast-forward button fast right speed media", category: "controls" },
  { emoji: "⏭️", name: "next track button skip forward right media", category: "controls" },
  { emoji: "⏯️", name: "play or pause button toggle switch media state", category: "controls" },
  { emoji: "◀️", name: "reverse button triangle left back media", category: "controls" },
  { emoji: "⏪", name: "fast reverse button fast left speed back media", category: "controls" },
  { emoji: "⏮️", name: "previous track button skip back left media", category: "controls" },
  { emoji: "🔼", name: "upwards button triangle up higher increase scroll", category: "controls" },
  { emoji: "🔽", name: "downwards button triangle down lower decrease scroll", category: "controls" },
  { emoji: "⏬", name: "fast down button double down lower lower decrease", category: "controls" },
  { emoji: "⏸️", name: "pause button twin bars hold stay media stop", category: "controls" },
  { emoji: "⏹️", name: "stop button square terminate exit media clear", category: "controls" },
  { emoji: "⏺️", name: "record button red circle recording media mic camera", category: "controls" },
  { emoji: "⏏️", name: "eject button push out CD DVD tray open", category: "controls" },
  { emoji: "🎦", name: "cinema movie film show theatre project", category: "controls" },
  { emoji: "🔅", name: "low brightness dimmer light low screen energy", category: "controls" },
  { emoji: "🔆", name: "high brightness bright light high screen visibility", category: "controls" },
  { emoji: "📶", name: "antenna bars cellular signal network coverage telecom data", category: "controls" },
  { emoji: "📳", name: "vibration mode smartphone ring silent buzz alerts", category: "controls" },
  { emoji: "📴", name: "mobile phone off power shutdown sleep screen black", category: "controls" },

  // Miscellaneous Symbols
  { emoji: "♀️", name: "female sign woman gender lady girl pink", category: "symbols" },
  { emoji: "♂️", name: "male sign man gender guy boy blue", category: "symbols" },
  { emoji: "⚧️", name: "transgender sign gender identity pride symbol", category: "symbols" },
  { emoji: "✖️", name: "multiply math times cross wrong cancel x", category: "symbols" },
  { emoji: "➕", name: "plus math add join positive cross sum", category: "symbols" },
  { emoji: "➖", name: "minus math subtract take remove negative line", category: "symbols" },
  { emoji: "➗", name: "divide math ratio split division fractions", category: "symbols" },
  { emoji: "♾️", name: "infinity endless loop limit forever sci-fi math", category: "symbols" },
  { emoji: "‼️", name: "double exclamation mark red alert warning danger accent", category: "symbols" },
  { emoji: "⁉️", name: "exclamation question mark shock confusion surprise alert", category: "symbols" },
  { emoji: "❓", name: "red question mark query confusion ask who help doubt", category: "symbols" },
  { emoji: "❔", name: "white question mark query outline ask doubt confusion", category: "symbols" },
  { emoji: "❕", name: "white exclamation mark alert warning attention accent", category: "symbols" },
  { emoji: "❗", name: "red exclamation mark alert danger watch out attention warning", category: "symbols" },
  { emoji: "〰️", name: "wavy dash squiggle tilde wave line curve", category: "symbols" },
  { emoji: "💱", name: "currency exchange money swap trade transaction banks", category: "symbols" },
  { emoji: "💲", name: "heavy dollar sign money usd currency cash price", category: "symbols" },
  { emoji: "🪯", name: "khanda sikhism religion faith double-edged sword symbol", category: "symbols" },
  { emoji: "🔱", name: "trident emblem sea poseidon weapon forks status", category: "symbols" },
  { emoji: "📛", name: "name badge red flower label blank tags sticker", category: "symbols" },
  { emoji: "🔰", name: "japanese symbol for beginner driver shield green yellow badge", category: "symbols" },
  { emoji: "⭕", name: "heavy large circle red o correct right ring empty", category: "symbols" },
  { emoji: "✅", name: "green check mark button thick success pass approved", category: "symbols" },
  { emoji: "☑️", name: "ballot box with check checked list option select box", category: "symbols" },
  { emoji: "✔️", name: "check mark symbol tick pass correct completed true verified", category: "symbols" },
  { emoji: "❌", name: "cross mark thick red wrong error cancel x failed", category: "symbols" },
  { emoji: "❎", name: "cross mark button green box correct clear cancel x", category: "symbols" },
  { emoji: "➰", name: "curly loop rope string knot spiral line", category: "symbols" },
  { emoji: "➿", name: "double curly loop recording wire cassette infinity shape", category: "symbols" },
  { emoji: "〽️", name: "part alternation mark japanese music punctuation sign lyric", category: "symbols" },
  { emoji: "✳️", name: "eight-spoked asterisk green square star math multiplier", category: "symbols" },
  { emoji: "✴️", name: "eight-pointed star orange square glowing sparks starburst", category: "symbols" },
  { emoji: "❇️", name: "sparkle green square star spark flash decoration", category: "symbols" },
  { emoji: "🪮", name: "hair pick comb Afro hair styled volume beauty", category: "symbols" },

  // Letters & Text boxes
  { emoji: "🔠", name: "input latin uppercase letters alphabet caps typing", category: "letters" },
  { emoji: "🔡", name: "input latin lowercase letters alphabet text typing", category: "letters" },
  { emoji: "🔢", name: "input numbers digits 1234 math count keyboard", category: "letters" },
  { emoji: "🔣", name: "input symbols punctuation characters special math keyboard", category: "letters" },
  { emoji: "🔤", name: "input latin letters abc alphabet spelling keyboard typing", category: "letters" },
  { emoji: "🅰️", name: "A button red blood type A letter capital letter alpha", category: "letters" },
  { emoji: "🆎", name: "AB button red blood type AB letter caps capital letters", category: "letters" },
  { emoji: "🅱️", name: "B button red blood type B letter capital caps beta", category: "letters" },
  { emoji: "🆑", name: "CL button red clear delete erase screens reset", category: "letters" },
  { emoji: "🆒", name: "COOL button blue square trendy awesome fashion style", category: "letters" },
  { emoji: "🆓", name: "FREE button blue square no cost zero promo gift", category: "letters" },
  { emoji: "ℹ️", name: "information sign info blue circle letter i help guide", category: "letters" },
  { emoji: "🆔", name: "ID button blue square identity card passport verification badge", category: "letters" },
  { emoji: "Ⓜ️", name: "M sign blue circle metro subway transit middle capital letter", category: "letters" },
  { emoji: "🆕", name: "NEW button blue square fresh update latest releases product", category: "letters" },
  { emoji: "🆖", name: "NG button blue square no good fail rejected negative", category: "letters" },
  { emoji: "🅾️", name: "O button red blood type O zero capital letter circle", category: "letters" },
  { emoji: "🆗", name: "OK button blue square correct pass yes confirmed approved", category: "letters" },
  { emoji: "🅿️", name: "parking button blue square park car vehicle roads stop", category: "letters" },
  { emoji: "🆘", name: "SOS button red square help emergency rescue warning danger", category: "letters" },
  { emoji: "🆙", name: "UP button blue square higher upgrade level speed increase", category: "letters" },
  { emoji: "🆚", name: "VS button orange square versus fight battle match competitor", category: "letters" },

  // Flags
  { emoji: "🏁", name: "chequered flag checkered race finish winner start motorsport", category: "flags" },
  { emoji: "flag", name: "red triangular flag golf course marker signal warning", category: "flags" }, // flag 🚩
  { emoji: "🚩", name: "red triangular flag golf course marker signal warning", category: "flags" },
  { emoji: "🎌", name: "crossed flags japanese festivals ceremony holiday celebrate", category: "flags" },
  { emoji: "🏴", name: "black flag pirate rebel outline flag dark", category: "flags" },
  { emoji: "🏳️", name: "white flag peace surrender truce blank flag light", category: "flags" },
  { emoji: "🏳️‍🌈", name: "rainbow flag pride LGBT community colors love diversity", category: "flags" },
  { emoji: "🏳️‍⚧️", name: "transgender flag pride blue pink white stripes identity community", category: "flags" },
  { emoji: "🏴‍☠️", name: "pirate flag skull crossbones jolly roger sea rebels outlaw", category: "flags" },
  { emoji: "🇺🇸", name: "USA flag United States of America american", category: "flags" },
  { emoji: "🇬🇧", name: "UK flag United Kingdom Great Britain union jack", category: "flags" },
  { emoji: "🇯🇵", name: "Japan flag Land of Rising Sun nihon nippon", category: "flags" },
  { emoji: "🇨🇳", name: "China flag Red Dragon chinese east asia", category: "flags" },
  { emoji: "🇩🇪", name: "Germany flag black red gold german Deutschland", category: "flags" },
  { emoji: "🇫🇷", name: "France flag tricolor French republique blue white red", category: "flags" },
  { emoji: "🇮🇳", name: "India flag tricolor saffron white green ashoka chakra indian", category: "flags" },
  { emoji: "🇪🇺", name: "Europe flag European Union EU blue yellow stars", category: "flags" },
  { emoji: "🇨🇦", name: "Canada flag maple leaf canadian red white", category: "flags" },
  { emoji: "🇦🇺", name: "Australia flag southern cross union jack australian", category: "flags" },
  { emoji: "🇧🇷", name: "Brazil flag green yellow blue globe brasil", category: "flags" }
];
